### ISSUE TITLE
Licencia GPL

### ISSUE THREAD

**Issue by Nyveon** [matias-saavedra-g/ucursednt#1]
Hola!

Me encanta que alguien esté continuando con la idea del proyecto de [tU-Cursos](https://github.com/Nyveon/tU-Cursos) independiente de si está bajo otro nombre o no! Especialmente considerando que el original estaba un poco abandonado. Las funcionalidades y correcciones que has agregado están geniales 🔥

Al revisar el historial de commits, noté que usaste bastante código directamente del nuestro, lo cual está bien 👍. Sin embargo, cambiaste la licencia a MIT en el commit 6e7d596, cuando el repositorio original está bajo la licencia [GPL](https://github.com/Nyveon/tU-Cursos/blob/main/LICENSE). Uno de los términos de la licencia GPL es que toda obra derivada o que use el código también debe estar licenciada bajo GPL. Puedes leer una explicación de la diferencia entre los dos [aquí](https://www.endorlabs.com/learn/open-source-licensing-simplified-a-comparative-overview-of-popular-licenses#:~:text=One%20of%20the%20key%20differences,released%20under%20the%20same%20license).

Considerando que indirectamente estás ofreciendo código bajo una licencia más permisiva, apreciaría si pudieras cambiarlo de vuelta a GPL c:

Adicionalmente, en partes del código se encuentran comentarios como `// Créditos a https://github.com/Nyveon/tU-Cursos por la inspiración inicial.`. Según la licencia GPL, cuando usas código directamente del repositorio original deberías ser un poco más explícito. Decir que fue solo inspiración da a entender que solo lo leíste y te inspiraste, cuando en realidad te basaste en el código original. Algo como `// Basado en https://github.com/Nyveon/tU-Cursos - Modificado por <tu usuario/nombre> el <fecha de primera modificación>` estaría más en el espíritu de la licencia GPL (más de detalle en la sección 5 de la licencia, sobre modificación de código fuente).

Si quieres ponerte en contacto, mi Telegram es @Eric_PK y mi Discord es @Nyveon. Y nuevamente, encuentro genial lo que estás haciendo, ojalá no tomes esto como una crítica a tu trabajo en sí 🙏.

Saludos, Eric.

**Comment by matias-saavedra-g** [comment]
¡Hola Nyveon!

Gracias por tus comentarios y por tomarte el tiempo de revisar mi trabajo. Tienes toda la razón con respecto a la licencia GPL. Ya he corregido el error y he cambiado la licencia de vuelta a GPL en todo el repositorio. También he actualizado los comentarios para reflejar de manera más precisa el uso del código original.

Estoy muy interesado en aprender más sobre las formalidades legales en GitHub y me alegra que me hayas señalado estos puntos.

¡Saludos y gracias nuevamente por tus sugerencias y alcances!
